// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyE78Sbrk5sveFhXx_a1Zv-yO25a3vAUs',
    appId: '1:198673287653:web:689aec533cd2f3fa1c070c',
    messagingSenderId: '198673287653',
    projectId: 'padie-3656d',
    authDomain: 'padie-3656d.firebaseapp.com',
    storageBucket: 'padie-3656d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU_c1r1-OwilSBWTteBzHe3GB7jwYb-tc',
    appId: '1:198673287653:android:36d9577bce28818d1c070c',
    messagingSenderId: '198673287653',
    projectId: 'padie-3656d',
    storageBucket: 'padie-3656d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcuu3MholR2HeLAbtB2tDYaBNsh3Q_b9E',
    appId: '1:198673287653:ios:6c5c35d397f48a3b1c070c',
    messagingSenderId: '198673287653',
    projectId: 'padie-3656d',
    storageBucket: 'padie-3656d.appspot.com',
    iosClientId: '198673287653-a5hsn1dbp92jccg4te45m7jqv5c4ovkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.padieMobile',
  );
}
